spring.application.name=charging_station_web

spring.data.mongodb.database=ChargingSystemDB
spring.data.mongodb.uri=mongodb+srv://DucDN13:16122003Dnd@mychargingappcluster.fckhf3p.mongodb.net/ChargingSystemDB?appName=MyChargingAppCluster
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=milkee1423@gmail.com
spring.mail.password=jfpw zahy yaqy ozjo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.test-connection=false
